### ISSUE TITLE
invalide response error 

### ISSUE THREAD

**Issue by daproject85** [MRokas/PogoPlayer#2]
Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/Users/Rocky/Pokemon/PogoPlayer/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/Users/Rocky/Pokemon/PogoPlayer/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by MRokas** [comment]
Could you update to latest version and try again? Thanks!

**Comment by daproject85** [comment]
done, so you advise picking trainer name anyways?

**Comment by daproject85** [comment]
Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/Users/Rocky/Pokemon/PogoPlayer/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/Users/Rocky/Pokemon/PogoPlayer/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)  




same issue

**Comment by MRokas** [comment]
I've made another update, so it should give more clear errors(message + error stack) - could you try again? thanks!

**Comment by daproject85** [comment]
Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/Users/Rocky/Pokemon/PogoPlayer/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/Users/Rocky/Pokemon/PogoPlayer/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by MRokas** [comment]
Hm.. that's weird af :/

could you shows accounts.csv content? ?(make sure to change password to `**********` or something alike`

**Comment by daproject85** [comment]
ptc,XXXXX,XXXXX,37.323368-121.950196
ptc,XXXXX,XXXXXX,37.323368-121.950196

**Comment by MRokas** [comment]
`37.323368-121.950196` change to `37.323368,-121.950196`

**Comment by daproject85** [comment]
Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/Users/Rocky/Pokemon/PogoPlayer/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/Users/Rocky/Pokemon/PogoPlayer/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Rocky/Pokemon/PogoPlayer/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by MRokas** [comment]
are you sure you've latest `pogo.js` file version? It should work fine now :/

**Comment by daproject85** [comment]
wait r u on discord?? it iwll make life easier

**Comment by MRokas** [comment]
yes, I'm. MRokas#2853

**Comment by nikos90** [comment]
Happening to me too

**Comment by MRokas** [comment]
@nikos90 - are you using latest version? what is your node version?

**Comment by nikos90** [comment]
@MRokas  false alarm! It worked after a few tries.
Looks like the registrations were inactive
