### ISSUE TITLE
ERROR: Error: Invalid response received from PTC login 

### ISSUE THREAD

**Issue by rrbailey89** [MRokas/PogoPlayer#9]
I always seem to get this error it seems that its almost always for 3 accounts no matter the amount of accounts. This error will repeat 3 times and then work but leave out 3 random accounts when assigning names. 

```
Failed to initialize client... ERROR: Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (F:\Ray\Downloads\PoGoMap\ptc-acc-gen\node_modules\pogobuf\pogobuf\pogobuf.ptclogin.js:108:28)
    at Request.self.callback (F:\Ray\Downloads\PoGoMap\ptc-acc-gen\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (F:\Ray\Downloads\PoGoMap\ptc-acc-gen\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (F:\Ray\Downloads\PoGoMap\ptc-acc-gen\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by MRokas** [comment]
This is an issue related to pogobuf, nothing I can do about it.
